### ISSUE TITLE
Installation instructions ?

### ISSUE THREAD

**Issue by Foxi352** [dfir-iris/iris-web#180]
I wanted to quickly try iris-web, using all defaults, to see if it suits my needs. Sadly after several tries i'm still unable to get it up and running in a test lab. What else is to do except following the 4 commands given in README.md ?

Copied `.env.model` to `.env`. Nothing changed, as just for a "quick" test.

**Tried in Photon OS 4.0**
```
iriswebapp_nginx   | 2023/01/31 13:28:03 [emerg] 1#1: cannot load certificate "/www/certs/iris_dev_cert.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/www/certs/iris_dev_cert.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
iriswebapp_nginx   | nginx: [emerg] cannot load certificate "/www/certs/iris_dev_cert.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/www/certs/iris_dev_cert.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
```

**Tried in Debian 11**

Thought that maybe Photon OS is a bit more special i tried in newly installed Debian 11 with included `Docker version 20.10.5+dfsg1, build 55c4c88`

```
root@docker-temp:~/git/iris-web# git branch -v
* (HEAD detached at v1.4.5) 59108243 Bump version: 1.4.4 → 1.4.5
```
```
docker-compose build
docker-compose up
```
```
Attaching to iris-web_db_1, rabbitmq, iris-web_app_1, iriswebapp_nginx, iris-web_worker_1
app_1       | Running iriswebapp ...
db_1        |
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        |
db_1        | 2023-01-31 13:48:15.027 UTC [1] LOG:  starting PostgreSQL 12.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1        | 2023-01-31 13:48:15.027 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2023-01-31 13:48:15.027 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2023-01-31 13:48:15.038 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2023-01-31 13:48:15.106 UTC [23] LOG:  database system was shut down at 2023-01-31 13:41:13 UTC
db_1        | 2023-01-31 13:48:15.123 UTC [1] LOG:  database system is ready to accept connections
app_1       | [2023-01-31 13:48:17 +0000] [8] [INFO] Starting gunicorn 20.1.0
app_1       | [2023-01-31 13:48:17 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
app_1       | [2023-01-31 13:48:17 +0000] [8] [INFO] Using worker: eventlet
app_1       | [2023-01-31 13:48:17 +0000] [10] [INFO] Booting worker with pid: 10
app_1       | 2023-01-31 13:48:20 :: INFO :: post_init :: run_post_init :: IRIS v1.4.5
app_1       | 2023-01-31 13:48:20 :: INFO :: post_init :: run_post_init :: Running post initiation steps
app_1       | 2023-01-31 13:48:20 :: INFO :: post_init :: run_post_init :: Creating all Iris tables
db_1        | 2023-01-31 13:48:20.853 UTC [30] FATAL:  password authentication failed for user "raptor"
db_1        | 2023-01-31 13:48:20.853 UTC [30] DETAIL:  Role "raptor" does not exist.
db_1        | 	Connection matched pg_hba.conf line 99: "host all all all md5"
app_1       | [2023-01-31 13:48:20 +0000] [10] [ERROR] Exception in worker process
app_1       | Traceback (most recent call last):
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
app_1       |     return fn()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
app_1       |     return _ConnectionFairy._checkout(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
app_1       |     fairy = _ConnectionRecord.checkout(pool)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
app_1       |     rec = pool._do_get()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
app_1       |     self._dec_overflow()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
app_1       |     compat.raise_(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
app_1       |     raise exception
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
app_1       |     return self._create_connection()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
app_1       |     return _ConnectionRecord(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
app_1       |     self.__connect()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
app_1       |     pool.logger.debug("Error on connect(): %s", e)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
app_1       |     compat.raise_(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
app_1       |     raise exception
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
app_1       |     self.dbapi_connection = connection = pool._invoke_creator(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
app_1       |     return dialect.connect(*cargs, **cparams)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
app_1       |     return self.dbapi.connect(*cargs, **cparams)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
app_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
app_1       |     state = conn.poll()
app_1       | psycopg2.OperationalError: FATAL:  password authentication failed for user "raptor"
app_1       |
app_1       |
app_1       | The above exception was the direct cause of the following exception:
app_1       |
app_1       | Traceback (most recent call last):
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
app_1       |     worker.init_process()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
app_1       |     super().init_process()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
app_1       |     self.load_wsgi()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
app_1       |     self.wsgi = self.app.wsgi()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
app_1       |     self.callable = self.load()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
app_1       |     return self.load_wsgiapp()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
app_1       |     return util.import_app(self.app_uri)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
app_1       |     mod = importlib.import_module(module)
app_1       |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
app_1       |     return _bootstrap._gcd_import(name[level:], package, level)
app_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
app_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
app_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
app_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
app_1       |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
app_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
app_1       |   File "/iriswebapp/app/__init__.py", line 102, in <module>
app_1       |     from app import views
app_1       |   File "/iriswebapp/app/views.py", line 86, in <module>
app_1       |     run_post_init(development=app.config["DEVELOPMENT"])
app_1       |   File "/iriswebapp/app/post_init.py", line 72, in run_post_init
app_1       |     db.create_all(bind=None)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
app_1       |     self._execute_for_all_tables(app, bind, 'create_all')
app_1       |   File "/opt/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
app_1       |     op(bind=self.get_engine(app, bind), **extra)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
app_1       |     bind._run_ddl_visitor(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3116, in _run_ddl_visitor
app_1       |     with self.begin() as conn:
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3032, in begin
app_1       |     conn = self.connect(close_with_result=close_with_result)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
app_1       |     return self._connection_cls(self, close_with_result=close_with_result)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
app_1       |     else engine.raw_connection()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
app_1       |     return self._wrap_pool_connect(self.pool.connect, _connection)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
app_1       |     Connection._handle_dbapi_exception_noconnection(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
app_1       |     util.raise_(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
app_1       |     raise exception
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
app_1       |     return fn()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
app_1       |     return _ConnectionFairy._checkout(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
app_1       |     fairy = _ConnectionRecord.checkout(pool)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
app_1       |     rec = pool._do_get()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
app_1       |     self._dec_overflow()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
app_1       |     compat.raise_(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
app_1       |     raise exception
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
app_1       |     return self._create_connection()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
app_1       |     return _ConnectionRecord(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
app_1       |     self.__connect()
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
app_1       |     pool.logger.debug("Error on connect(): %s", e)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
app_1       |     compat.raise_(
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
app_1       |     raise exception
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
app_1       |     self.dbapi_connection = connection = pool._invoke_creator(self)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
app_1       |     return dialect.connect(*cargs, **cparams)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
app_1       |     return self.dbapi.connect(*cargs, **cparams)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
app_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
app_1       |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
app_1       |     state = conn.poll()
app_1       | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "raptor"
app_1       |
app_1       | (Background on this error at: https://sqlalche.me/e/14/e3q8)
app_1       | [2023-01-31 13:48:20 +0000] [10] [INFO] Worker exiting (pid: 10)
worker_1    | IRISwebapp is unavailable - sleeping
app_1       | [2023-01-31 13:48:21 +0000] [8] [INFO] Shutting down: Master
app_1       | [2023-01-31 13:48:21 +0000] [8] [INFO] Reason: Worker failed to boot.
worker_1    | IRISwebapp is unavailable - sleeping
iriswebapp_nginx | 2023/01/31 13:48:22 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: iris.app.dev, request: "GET / HTTP/1.1", upstream: "http://172.22.0.4:8000/", host: "127.0.0.1:8443"
iriswebapp_nginx | 127.0.0.1 - - [31/Jan/2023:13:48:22 +0000] "GET / HTTP/1.1" 502 497 "-" "curl/7.64.0" "-"
iriswebapp_nginx | 2023/01/31 13:48:22 [info] 12#12: *1 client 127.0.0.1 closed keepalive connection
rabbitmq    | 2023-01-31 13:48:22.712386+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
rabbitmq    | 2023-01-31 13:48:22.725130+00:00 [notice] <0.229.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
rabbitmq    | 2023-01-31 13:48:22.757674+00:00 [notice] <0.229.0> Logging: configured log handlers are now ACTIVE
rabbitmq    | 2023-01-31 13:48:23.228899+00:00 [info] <0.229.0> ra: starting system quorum_queues
rabbitmq    | 2023-01-31 13:48:23.229060+00:00 [info] <0.229.0> starting Ra system: quorum_queues in directory: /var/lib/rabbitmq/mnesia/rabbit@ee1109354367/quorum/rabbit@ee1109354367

------- shortened -------

rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  node           : rabbit@ee1109354367
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  home dir       : /var/lib/rabbitmq
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  cookie hash    : +XJY+iHrgqxinEUxZsIyZw==
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  log(s)         : /var/log/rabbitmq/rabbit@ee1109354367_upgrade.log
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>                 : <stdout>
rabbitmq    | 2023-01-31 13:48:23.442618+00:00 [info] <0.229.0>  database dir   : /var/lib/rabbitmq/mnesia/rabbit@ee1109354367
worker_1    | IRISwebapp is unavailable - sleeping
worker_1    | IRISwebapp is unavailable - sleeping
worker_1    | IRISwebapp is unavailable - sleeping
worker_1    | IRISwebapp is unavailable - sleeping
iriswebapp_nginx | 2023/01/31 13:48:27 [error] 12#12: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: iris.app.dev, request: "GET / HTTP/1.1", upstream: "http://172.22.0.4:8000/", host: "127.0.0.1:8443"
iriswebapp_nginx | 127.0.0.1 - - [31/Jan/2023:13:48:27 +0000] "GET / HTTP/1.1" 502 497 "-" "curl/7.64.0" "-"
iriswebapp_nginx | 2023/01/31 13:48:27 [info] 12#12: *3 client 127.0.0.1 closed keepalive connection
worker_1    | IRISwebapp is unavailable - sleeping
worker_1    | IRISwebapp is unavailable - sleeping
rabbitmq    | 2023-01-31 13:48:29.867486+00:00 [info] <0.229.0> Running boot step pre_boot defined by app rabbit
rabbitmq    | 2023-01-31 13:48:29.867611+00:00 [info] <0.229.0> Running boot step rabbit_global_counters defined by app rabbit
rabbitmq    | 2023-01-31 13:48:29.869047+00:00 [info] <0.229.0> Running boot step rabbit_osiris_metrics defined by app rabbit
rabbitmq    | 2023-01-31 13:48:29.869345+00:00 [info] <0.229.0> Running boot step rabbit_core_metrics defined by app rabbit
rabbitmq    | 2023-01-31 13:48:29.871670+00:00 [info] <0.229.0> Running boot step rabbit_alarm defined by app rabbit

------- shortened -------

rabbitmq    |  completed with 4 plugins.
rabbitmq    | 2023-01-31 13:48:31.077265+00:00 [info] <0.721.0> Server startup complete; 4 plugins started.
rabbitmq    | 2023-01-31 13:48:31.077265+00:00 [info] <0.721.0>  * rabbitmq_prometheus
rabbitmq    | 2023-01-31 13:48:31.077265+00:00 [info] <0.721.0>  * rabbitmq_management
rabbitmq    | 2023-01-31 13:48:31.077265+00:00 [info] <0.721.0>  * rabbitmq_web_dispatch
rabbitmq    | 2023-01-31 13:48:31.077265+00:00 [info] <0.721.0>  * rabbitmq_management_agent
worker_1    | IRISwebapp is unavailable - sleeping
worker_1    | IRISwebapp is unavailable - sleeping
iriswebapp_nginx | 2023/01/31 13:48:32 [error] 12#12: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: iris.app.dev, request: "GET / HTTP/1.1", upstream: "http://172.22.0.4:8000/", host: "127.0.0.1:8443"
iriswebapp_nginx | 127.0.0.1 - - [31/Jan/2023:13:48:32 +0000] "GET / HTTP/1.1" 502 497 "-" "curl/7.64.0" "-"
iriswebapp_nginx | 2023/01/31 13:48:32 [info] 12#12: *5 client 127.0.0.1 closed keepalive connection
worker_1    | IRISwebapp is unavailable - sleeping

[iriswebapp_nginx error and subsequent worker_1 error continue non-stop]
```

**Comment by whikernel** [comment]
Hi @Foxi352 

There are nothing else to do than the steps specified in the documention. It looks like the database was already spin up at some point and is already initialised. 
If that's a fresh install, could you please try the following from the root of the project ? 

```bash 
# Stop the dockers and remove all the persistent data 
docker-compose down --volumes 

# Build the dockers and force to not use the cache
docker-compose build --no-cache 

# Spin up the dockers 
docker-compose up 
```

**Comment by Ektoplasma** [comment]
I had a similar issue on a specific Linux distribution. The issue was related to the umask which was too restrictive (0027). Changing the umask to 0022 can fix the issue.

**Comment by Foxi352** [comment]
@Ektoplasma Thanks for the hint. It worked :thumbsup:

Comparing the repos on both test machines showed the difference. Most directories where created chmod 750 on the non working system, and 755 on the working system. I was so concentrated on file permissions that i completely forgot to check directory permissions :unamused:. I changed umask to 0022 and restarted from scratch and it worked immediately !
