### ISSUE TITLE
[BUG] DFIR-IRIS Docker failing with error 'FATAL:  password authentication failed for user "postgres"'

### ISSUE THREAD

**Issue by trevor-arthur** [dfir-iris/iris-web#228]
**Describe the bug**
I am trying to install DFIR-IRIS for the first time on docker. I have followed every step in the guide, but any time I try to docker compose up, there is a fatal error around failed password authentication for user "postgres". This happens whether I use the default .env or I add my own passwords to .env.

**To Reproduce**
git clone https://github.com/dfir-iris/iris-web.git
cd iris-web
git checkout v2.0.2
cp .env.model .env
docker-compose build
docker-compose up

**Expected behavior**
DFIR-IRIS web app should be able to connect to the database and successfully run the web application.

**System:**
 - OS: Ubuntu 22.04.2 LTS
 - Docker: Docker version 23.0.4, build f480fb1

![Screenshot 2023-04-25 at 6 49 00 PM](https://user-images.githubusercontent.com/107289372/234445157-5f7cdc92-546e-4f8d-b026-1ccf51eeb126.png)

**Log output**
`root@ip-10-7-1-14:/opt/iris-web# docker-compose up
Starting iriswebapp_db       ... done
Starting iriswebapp_rabbitmq ... done
Starting iriswebapp_app      ... done
Starting iriswebapp_worker   ... done
Starting iriswebapp_nginx    ... done
Attaching to iriswebapp_db, iriswebapp_rabbitmq, iriswebapp_app, iriswebapp_nginx, iriswebapp_worker
iriswebapp_app | Running iriswebapp ...
iriswebapp_app | [2023-04-26 01:47:32 +0000] [8] [INFO] Starting gunicorn 20.1.0
iriswebapp_app | [2023-04-26 01:47:32 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
iriswebapp_app | [2023-04-26 01:47:32 +0000] [8] [INFO] Using worker: eventlet
iriswebapp_db |
iriswebapp_db | PostgreSQL Database directory appears to contain a database; Skipping initialization
iriswebapp_db |
iriswebapp_db | 2023-04-26 01:47:31.876 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
iriswebapp_db | 2023-04-26 01:47:31.876 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
iriswebapp_db | 2023-04-26 01:47:31.876 UTC [1] LOG:  listening on IPv6 address "::", port 5432
iriswebapp_db | 2023-04-26 01:47:31.880 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
iriswebapp_db | 2023-04-26 01:47:31.922 UTC [22] LOG:  database system was shut down at 2023-04-26 01:42:15 UTC
iriswebapp_db | 2023-04-26 01:47:31.930 UTC [1] LOG:  database system is ready to accept connections
iriswebapp_app | [2023-04-26 01:47:32 +0000] [10] [INFO] Booting worker with pid: 10
iriswebapp_app | 2023-04-26 01:47:34 :: INFO :: post_init :: run_post_init :: IRIS v2.0.2
iriswebapp_app | 2023-04-26 01:47:34 :: INFO :: post_init :: run_post_init :: Running post initiation steps
iriswebapp_app | 2023-04-26 01:47:34 :: INFO :: post_init :: run_post_init :: Adding pgcrypto extension
iriswebapp_db | 2023-04-26 01:47:34.938 UTC [29] FATAL:  password authentication failed for user "postgres"
iriswebapp_db | 2023-04-26 01:47:34.938 UTC [29] DETAIL:  Password does not match for user "postgres".
iriswebapp_db | 	Connection matched pg_hba.conf line 99: "host all all all md5"
iriswebapp_app | 2023-04-26 01:47:34 :: ERROR :: views :: <module> :: Post init failed. IRIS not started
iriswebapp_app | Traceback (most recent call last):
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
iriswebapp_app |     return fn()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
iriswebapp_app |     return _ConnectionFairy._checkout(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
iriswebapp_app |     fairy = _ConnectionRecord.checkout(pool)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
iriswebapp_app |     rec = pool._do_get()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
iriswebapp_app |     self._dec_overflow()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
iriswebapp_app |     return self._create_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
iriswebapp_app |     return _ConnectionRecord(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
iriswebapp_app |     self.__connect()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
iriswebapp_app |     pool.logger.debug("Error on connect(): %s", e)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
iriswebapp_app |     self.dbapi_connection = connection = pool._invoke_creator(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
iriswebapp_app |     return dialect.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
iriswebapp_app |     return self.dbapi.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
iriswebapp_app |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
iriswebapp_app |     state = conn.poll()
iriswebapp_app | psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
iriswebapp_app |
iriswebapp_app |
iriswebapp_app | The above exception was the direct cause of the following exception:
iriswebapp_app |
iriswebapp_app | Traceback (most recent call last):
iriswebapp_app |   File "/iriswebapp/app/views.py", line 98, in <module>
iriswebapp_app |     run_post_init(development=app.config["DEVELOPMENT"])
iriswebapp_app |   File "/iriswebapp/app/post_init.py", line 85, in run_post_init
iriswebapp_app |     pg_add_pgcrypto_ext()
iriswebapp_app |   File "/iriswebapp/app/post_init.py", line 405, in pg_add_pgcrypto_ext
iriswebapp_app |     with db.engine.connect() as con:
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
iriswebapp_app |     return self._connection_cls(self, close_with_result=close_with_result)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
iriswebapp_app |     else engine.raw_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
iriswebapp_app |     return self._wrap_pool_connect(self.pool.connect, _connection)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
iriswebapp_app |     Connection._handle_dbapi_exception_noconnection(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
iriswebapp_app |     util.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
iriswebapp_app |     return fn()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
iriswebapp_app |     return _ConnectionFairy._checkout(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
iriswebapp_app |     fairy = _ConnectionRecord.checkout(pool)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
iriswebapp_app |     rec = pool._do_get()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
iriswebapp_app |     self._dec_overflow()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
iriswebapp_app |     return self._create_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
iriswebapp_app |     return _ConnectionRecord(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
iriswebapp_app |     self.__connect()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
iriswebapp_app |     pool.logger.debug("Error on connect(): %s", e)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
iriswebapp_app |     self.dbapi_connection = connection = pool._invoke_creator(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
iriswebapp_app |     return dialect.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
iriswebapp_app |     return self.dbapi.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
iriswebapp_app |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
iriswebapp_app |     state = conn.poll()
iriswebapp_app | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
iriswebapp_app |
iriswebapp_app | (Background on this error at: https://sqlalche.me/e/14/e3q8)
iriswebapp_app | [2023-04-26 01:47:34 +0000] [10] [ERROR] Exception in worker process
iriswebapp_app | Traceback (most recent call last):
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
iriswebapp_app |     return fn()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
iriswebapp_app |     return _ConnectionFairy._checkout(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
iriswebapp_app |     fairy = _ConnectionRecord.checkout(pool)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
iriswebapp_app |     rec = pool._do_get()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
iriswebapp_app |     self._dec_overflow()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
iriswebapp_app |     return self._create_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
iriswebapp_app |     return _ConnectionRecord(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
iriswebapp_app |     self.__connect()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
iriswebapp_app |     pool.logger.debug("Error on connect(): %s", e)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
iriswebapp_app |     self.dbapi_connection = connection = pool._invoke_creator(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
iriswebapp_app |     return dialect.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
iriswebapp_app |     return self.dbapi.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
iriswebapp_app |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
iriswebapp_app |     state = conn.poll()
iriswebapp_app | psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
iriswebapp_app |
iriswebapp_app |
iriswebapp_app | The above exception was the direct cause of the following exception:
iriswebapp_app |
iriswebapp_app | Traceback (most recent call last):
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
iriswebapp_app |     worker.init_process()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
iriswebapp_app |     super().init_process()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
iriswebapp_app |     self.load_wsgi()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
iriswebapp_app |     self.wsgi = self.app.wsgi()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
iriswebapp_app |     self.callable = self.load()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
iriswebapp_app |     return self.load_wsgiapp()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
iriswebapp_app |     return util.import_app(self.app_uri)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
iriswebapp_app |     mod = importlib.import_module(module)
iriswebapp_app |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
iriswebapp_app |     return _bootstrap._gcd_import(name[level:], package, level)
iriswebapp_app |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
iriswebapp_app |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
iriswebapp_app |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
iriswebapp_app |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
iriswebapp_app |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
iriswebapp_app |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
iriswebapp_app |   File "/iriswebapp/app/__init__.py", line 127, in <module>
iriswebapp_app |     from app import views
iriswebapp_app |   File "/iriswebapp/app/views.py", line 102, in <module>
iriswebapp_app |     raise e
iriswebapp_app |   File "/iriswebapp/app/views.py", line 98, in <module>
iriswebapp_app |     run_post_init(development=app.config["DEVELOPMENT"])
iriswebapp_app |   File "/iriswebapp/app/post_init.py", line 85, in run_post_init
iriswebapp_app |     pg_add_pgcrypto_ext()
iriswebapp_app |   File "/iriswebapp/app/post_init.py", line 405, in pg_add_pgcrypto_ext
iriswebapp_app |     with db.engine.connect() as con:
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
iriswebapp_app |     return self._connection_cls(self, close_with_result=close_with_result)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
iriswebapp_app |     else engine.raw_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
iriswebapp_app |     return self._wrap_pool_connect(self.pool.connect, _connection)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
iriswebapp_app |     Connection._handle_dbapi_exception_noconnection(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
iriswebapp_app |     util.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
iriswebapp_app |     return fn()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
iriswebapp_app |     return _ConnectionFairy._checkout(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
iriswebapp_app |     fairy = _ConnectionRecord.checkout(pool)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
iriswebapp_app |     rec = pool._do_get()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
iriswebapp_app |     self._dec_overflow()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
iriswebapp_app |     return self._create_connection()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
iriswebapp_app |     return _ConnectionRecord(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
iriswebapp_app |     self.__connect()
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
iriswebapp_app |     pool.logger.debug("Error on connect(): %s", e)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
iriswebapp_app |     compat.raise_(
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
iriswebapp_app |     raise exception
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
iriswebapp_app |     self.dbapi_connection = connection = pool._invoke_creator(self)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
iriswebapp_app |     return dialect.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
iriswebapp_app |     return self.dbapi.connect(*cargs, **cparams)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
iriswebapp_app |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
iriswebapp_app |   File "/opt/venv/lib/python3.9/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
iriswebapp_app |     state = conn.poll()
iriswebapp_app | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
iriswebapp_app |
iriswebapp_app | (Background on this error at: https://sqlalche.me/e/14/e3q8)
iriswebapp_app | [2023-04-26 01:47:34 +0000] [10] [INFO] Worker exiting (pid: 10)
iriswebapp_worker | IRISwebapp is unavailable - sleeping
iriswebapp_app | [2023-04-26 01:47:35 +0000] [8] [INFO] Shutting down: Master
iriswebapp_app | [2023-04-26 01:47:35 +0000] [8] [INFO] Reason: Worker failed to boot.
iriswebapp_worker | IRISwebapp is unavailable - sleeping`

**Comment by whikernel** [comment]
Hi @trevor-arthur 

This might be due to setting some variables after an initial run. Postgres passwords are set the very first time IRIS runs and cannot be changed with the .env afterward. 
Please ensure that your passwords are quoted in the .env if they contain special characters.  

You then probably need to reset the IRIS entirely with the following: 

```
docker-compose down --volumes 
docker-compose build --no-cache 
docker-compose up 
```

Let me know if it works 👍

**Comment by whikernel** [comment]
@BETONGUNO - Can you confirm this is indeed due to the missing env_file? 
The needed envs for the DB are already given by the `environment` section, so it shouldn't impact this docker.  

One issue that can generate these types of issues are special chars in the password, specifically % as it is interpreted as a URL encode in the build of the DB URL.

**Comment by 4001982248998** [comment]
> Never mind, my issue was related to podman-compose

can you elaborate? Having the exact issue myself right now ;)

**Comment by trevor-spaniola** [comment]
> @trevor-arthur did you manage to get it run?

Apologies for the late reply. The team did end up getting it running, I believe the issue was related to having unquoted special characters in the .env values.

**Comment by ryanoleary26** [comment]
> Hi @trevor-arthur
> 
> This might be due to setting some variables after an initial run. Postgres passwords are set the very first time IRIS runs and cannot be changed with the .env afterward. Please ensure that your passwords are quoted in the .env if they contain special characters.
> 
> You then probably need to reset the IRIS entirely with the following:
> 
> ```
> docker-compose down --volumes 
> docker-compose build --no-cache 
> docker-compose up 
> ```
> 
> Let me know if it works 👍

@whikernel In interest of other users (myself included) who have encountered this issue, these commands worked and accepted the passwords I changed in .env.
