### ISSUE TITLE
[BUG] WEBHOOK MODULE ERRORs

### ISSUE THREAD

**Issue by CyberAbwehr** [dfir-iris/iris-web#311]
**Describe the bug**

I have build a webhook to send information to shuffle.
if I create a asset it works,
if I delete a asset I will get an error

CREATE A NEW ASSET

[2023-09-21 14:40:27,780: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[8095ad9b-cf73-4a26-9728-f51cc8335297] received
[2023-09-21 14:40:27,927: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_asset_create
[2023-09-21 14:40:27,952: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:40:27,966: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 14:40:27,966: INFO/ForkPoolWorker-9] Received on_postload_asset_create
[2023-09-21 14:40:27,966: INFO/ForkPoolWorker-9] Received on_postload_asset_create, None
[2023-09-21 14:40:27,966: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:40:28,663: INFO/ForkPoolWorker-9] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:40:28,672: INFO/ForkPoolWorker-9] Successfully processed hook on_postload_asset_create

DELETE A ASSET

[2023-09-21 14:41:07,465: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[7ef6f9bf-ada9-4401-825e-cda26b13c84e] received
[2023-09-21 14:41:07,666: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_asset_delete
[2023-09-21 14:41:07,911: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:41:07,928: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 14:41:07,928: INFO/ForkPoolWorker-9] Received on_postload_asset_delete
[2023-09-21 14:41:07,929: INFO/ForkPoolWorker-9] Received on_postload_asset_delete, None
[2023-09-21 14:41:07,929: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:41:07,930: CRITICAL/ForkPoolWorker-9] Failed to run hook on_postload_asset_delete with module iris_webhooks_module. Error 'int' object has no attribute 'user'
[2023-09-21 14:41:07,930: ERROR/ForkPoolWorker-9] 'int' object has no attribute 'user'
Traceback (most recent call last):
File "/iriswebapp/app/iris_engine/module_handler/module_handler.py", line 480, in task_hook_wrapper
task_status = mod_inst.hooks_handler(hook_name, hook_ui_name, data=_obj)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 163, in hooks_handler
status = self._handle_hook(hook_name, hook_ui_name, data=data)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 217, in _handle_hook
self._do_web_hook(hook_name, data, hook, server_url)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 270, in _do_web_hook
user_name = data[0].user.name if data[0].user else 'N/A'
AttributeError: 'int' object has no attribute 'user'

IRIS server version:
v2.3.2
Database revision:
65168cb6cc90
Min. API version supported:
2.0.0
Max. API version supported:
2.0.3
Min. module interface version supported:
1.1
Max. module interface version supported:
1.2.0

The same problem with a case

CREATE A CASE

[2023-09-21 14:56:52,009: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[5b6e8dfb-1b04-4823-9777-beba9fcd40ce] received
[2023-09-21 14:56:52,118: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_task_create
[2023-09-21 14:56:52,136: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:52,145: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 14:56:52,145: INFO/ForkPoolWorker-9] Received on_postload_task_create
[2023-09-21 14:56:52,149: INFO/ForkPoolWorker-9] Received on_postload_task_create, None
[2023-09-21 14:56:52,149: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:52,328: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[b5b62d11-547c-4997-8ff7-bb2187243f00] received
[2023-09-21 14:56:52,610: INFO/ForkPoolWorker-2] Calling module iris_webhooks_module for hook on_postload_task_create
[2023-09-21 14:56:52,647: INFO/ForkPoolWorker-2] Retrieved server configuration
[2023-09-21 14:56:52,674: INFO/ForkPoolWorker-2] Module has initiated
[2023-09-21 14:56:52,675: INFO/ForkPoolWorker-2] Received on_postload_task_create
[2023-09-21 14:56:52,676: INFO/ForkPoolWorker-2] Received on_postload_task_create, None
[2023-09-21 14:56:52,679: INFO/ForkPoolWorker-2] Retrieved server configuration
[2023-09-21 14:56:52,718: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[e1979891-e1af-43c7-b701-2ba90549d91e] received
[2023-09-21 14:56:53,271: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[28d93eae-a3c6-416b-894b-cd2843e7d5e4] received
[2023-09-21 14:56:53,314: INFO/ForkPoolWorker-3] Calling module iris_webhooks_module for hook on_postload_task_create
[2023-09-21 14:56:53,426: INFO/ForkPoolWorker-3] Retrieved server configuration
[2023-09-21 14:56:53,525: INFO/ForkPoolWorker-3] Module has initiated
[2023-09-21 14:56:53,530: INFO/ForkPoolWorker-3] Received on_postload_task_create
[2023-09-21 14:56:53,531: INFO/ForkPoolWorker-3] Received on_postload_task_create, None
[2023-09-21 14:56:53,531: INFO/ForkPoolWorker-3] Retrieved server configuration
[2023-09-21 14:56:54,049: INFO/ForkPoolWorker-9] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:54,063: INFO/ForkPoolWorker-9] Successfully processed hook on_postload_task_create
[2023-09-21 14:56:54,259: INFO/ForkPoolWorker-4] Calling module iris_webhooks_module for hook on_postload_task_create
[2023-09-21 14:56:54,399: INFO/ForkPoolWorker-4] Retrieved server configuration
[2023-09-21 14:56:54,448: INFO/ForkPoolWorker-4] Module has initiated
[2023-09-21 14:56:54,455: INFO/ForkPoolWorker-4] Received on_postload_task_create
[2023-09-21 14:56:54,456: INFO/ForkPoolWorker-4] Received on_postload_task_create, None
[2023-09-21 14:56:54,458: INFO/ForkPoolWorker-4] Retrieved server configuration
[2023-09-21 14:56:54,581: INFO/ForkPoolWorker-2] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:54,587: INFO/ForkPoolWorker-2] Successfully processed hook on_postload_task_create
[2023-09-21 14:56:54,931: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[ff44b50b-79c8-451a-b73f-33bf12de4d4b] received
[2023-09-21 14:56:55,345: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_task_create
[2023-09-21 14:56:55,555: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:55,774: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 14:56:55,776: INFO/ForkPoolWorker-9] Received on_postload_task_create
[2023-09-21 14:56:55,777: INFO/ForkPoolWorker-9] Received on_postload_task_create, None
[2023-09-21 14:56:55,777: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:56,158: INFO/ForkPoolWorker-3] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:56,172: INFO/ForkPoolWorker-3] Successfully processed hook on_postload_task_create
[2023-09-21 14:56:56,489: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[265d7eb0-e1e3-48a0-b9ee-329b01cd51be] received
[2023-09-21 14:56:56,698: INFO/ForkPoolWorker-2] Calling module iris_webhooks_module for hook on_postload_note_create
[2023-09-21 14:56:56,741: INFO/ForkPoolWorker-2] Retrieved server configuration
[2023-09-21 14:56:56,795: INFO/ForkPoolWorker-2] Module has initiated
[2023-09-21 14:56:56,795: INFO/ForkPoolWorker-2] Received on_postload_note_create
[2023-09-21 14:56:56,795: INFO/ForkPoolWorker-2] Received on_postload_note_create, None
[2023-09-21 14:56:56,795: INFO/ForkPoolWorker-2] Retrieved server configuration
[2023-09-21 14:56:57,011: INFO/ForkPoolWorker-4] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:57,023: INFO/ForkPoolWorker-4] Successfully processed hook on_postload_task_create
[2023-09-21 14:56:57,184: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[20bf1fad-545e-4dee-9076-55cbe6bdfea9] received
[2023-09-21 14:56:57,486: INFO/ForkPoolWorker-5] Calling module iris_webhooks_module for hook on_postload_note_create
[2023-09-21 14:56:57,514: INFO/ForkPoolWorker-5] Retrieved server configuration
[2023-09-21 14:56:57,570: INFO/ForkPoolWorker-5] Module has initiated
[2023-09-21 14:56:57,572: INFO/ForkPoolWorker-5] Received on_postload_note_create
[2023-09-21 14:56:57,573: INFO/ForkPoolWorker-5] Received on_postload_note_create, None
[2023-09-21 14:56:57,573: INFO/ForkPoolWorker-5] Retrieved server configuration
[2023-09-21 14:56:57,628: INFO/ForkPoolWorker-9] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:57,631: INFO/ForkPoolWorker-9] Successfully processed hook on_postload_task_create
[2023-09-21 14:56:57,983: INFO/ForkPoolWorker-2] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:57,994: INFO/ForkPoolWorker-2] Successfully processed hook on_postload_note_create
[2023-09-21 14:56:58,220: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[e17a2100-a0d6-4261-8cc2-16a59698883f] received
[2023-09-21 14:56:58,556: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_case_create
[2023-09-21 14:56:58,624: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:58,650: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 14:56:58,651: INFO/ForkPoolWorker-9] Received on_postload_case_create
[2023-09-21 14:56:58,652: INFO/ForkPoolWorker-9] Received on_postload_case_create, None
[2023-09-21 14:56:58,652: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 14:56:58,858: INFO/ForkPoolWorker-5] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:58,862: INFO/ForkPoolWorker-5] Successfully processed hook on_postload_note_create
[2023-09-21 14:56:59,652: INFO/ForkPoolWorker-9] Webhook SHUFFLE WEBHOOK - Payload delivered successfully, code 200.
[2023-09-21 14:56:59,662: INFO/ForkPoolWorker-9] Successfully processed hook on_postload_case_create

DELETE A CASE

[2023-09-21 15:02:10,957: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[7ada86cf-5e31-4d15-ae60-8697f0521ae8] received
[2023-09-21 15:02:11,033: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_case_delete
[2023-09-21 15:02:11,154: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 15:02:11,191: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 15:02:11,192: INFO/ForkPoolWorker-9] Received on_postload_case_delete
[2023-09-21 15:02:11,193: INFO/ForkPoolWorker-9] Received on_postload_case_delete, None
[2023-09-21 15:02:11,193: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 15:02:11,193: CRITICAL/ForkPoolWorker-9] Failed to run hook on_postload_case_delete with module iris_webhooks_module. Error 'int' object has no attribute 'user'
[2023-09-21 15:02:11,193: ERROR/ForkPoolWorker-9] 'int' object has no attribute 'user'
Traceback (most recent call last):
File "/iriswebapp/app/iris_engine/module_handler/module_handler.py", line 480, in task_hook_wrapper
task_status = mod_inst.hooks_handler(hook_name, hook_ui_name, data=_obj)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 163, in hooks_handler
status = self._handle_hook(hook_name, hook_ui_name, data=data)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 217, in _handle_hook
self._do_web_hook(hook_name, data, hook, server_url)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 260, in _do_web_hook
user_name = data[0].user.name if data[0].user else 'N/A'
AttributeError: 'int' object has no attribute 'user'

Same Error by adding a comment to a note

[2023-09-21 16:01:15,373: INFO/MainProcess] Task app.iris_engine.module_handler.module_handler.task_hook_wrapper[459c5717-af82-4a9c-b9f2-809578ff2813] received
[2023-09-21 16:01:15,447: INFO/ForkPoolWorker-9] Calling module iris_webhooks_module for hook on_postload_note_commented
[2023-09-21 16:01:15,681: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 16:01:15,716: INFO/ForkPoolWorker-9] Module has initiated
[2023-09-21 16:01:15,717: INFO/ForkPoolWorker-9] Received on_postload_note_commented
[2023-09-21 16:01:15,717: INFO/ForkPoolWorker-9] Received on_postload_note_commented, None
[2023-09-21 16:01:15,718: INFO/ForkPoolWorker-9] Retrieved server configuration
[2023-09-21 16:01:15,718: CRITICAL/ForkPoolWorker-9] Failed to run hook on_postload_note_commented with module iris_webhooks_module. Error 'dict' object has no attribute 'user'
[2023-09-21 16:01:15,718: ERROR/ForkPoolWorker-9] 'dict' object has no attribute 'user'
Traceback (most recent call last):
File "/iriswebapp/app/iris_engine/module_handler/module_handler.py", line 480, in task_hook_wrapper
task_status = mod_inst.hooks_handler(hook_name, hook_ui_name, data=_obj)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 163, in hooks_handler
status = self._handle_hook(hook_name, hook_ui_name, data=data)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 217, in _handle_hook
self._do_web_hook(hook_name, data, hook, server_url)
File "/opt/venv/lib/python3.9/site-packages/iris_webhooks_module/IrisWebHooksInterface.py", line 281, in _do_web_hook
user_name = data[0].user.name if data[0].user else 'N/A'
AttributeError: 'dict' object has no attribute 'user'

https://github.com/dfir-iris/iris-webhooks-module/issues/5

regards ;-)

**Comment by benibomba** [comment]
Were you able to solve this problem? I am facing the same problem

**Comment by whikernel** [comment]
Hello, 

We updated the module in the last version of IRIS. It should resolve the issue. - let us know
