### ISSUE TITLE
[FR] OpenID Connect / OAuth implementation

### ISSUE THREAD

**Issue by qfety** [dfir-iris/iris-web#370]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

**Is your feature request related to a problem? Please describe.**
I am trying to log in to DFIR-IRIS using Keycloak and OpenID Connect or OAuth. Unfortunately, DFIR-IRIS currently only offers login via local or LDAP authentication.

**Describe the solution you'd like**
Is an implementation of OAuth or OpenID Connect currently planned? 
Is there already an approximate release date for this?

**Describe alternatives you've considered**
Logging in via LDAP would be conceivable, but I would like to carry out the project using OpenID Connect/OAuth.

**Additional context**
none

**Comment by sim0nx** [comment]
It would be nice if you could support web-server authentication... that would allow for easy OIDC or other auth support.

**Comment by FideliusFalcon** [comment]
I've just started to look into deploying Iris, and I'm very surprised that it doesn't support OIDC or SAML. I really hope that somebody will pick up this feature

**Comment by richarson** [comment]
Hello.

This seems to be implemented in version 2.4.14 (unreleased) via #591 but I can't make it work, I get a 500 error when clicking "Use SSO"

I'll open a new bug report but thought to let you know in this issue as well.

**Comment by whikernel** [comment]
@richarson indeed the feature is still in beta. Would you have the logs of the webapp that generate the 500? 
You can do a `docker compose logs webapp` and click on `Use SSO`. You should have a stack trace showing what's wrong.

**Comment by richarson** [comment]
Hi!
Yes, I was about to open another issue but thought to check here first :smiley: 

Here you go:
```
iriswebapp_app       | 2024-11-01 22:58:29 :: ERROR :: app :: log_exception :: Exception on /oidc-login [GET]
iriswebapp_app       | Traceback (most recent call last):
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
iriswebapp_app       |     response = self.full_dispatch_request()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
iriswebapp_app       |     rv = self.handle_user_exception(e)
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
iriswebapp_app       |     rv = self.dispatch_request()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
iriswebapp_app       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
iriswebapp_app       |   File "/iriswebapp/app/blueprints/login/login_routes.py", line 192, in oidc_login
iriswebapp_app       |     login_url = auth_req.request(oidc_client.authorization_endpoint)
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/oic/oauth2/message.py", line 784, in request
iriswebapp_app       |     if "?" in location:
iriswebapp_app       | TypeError: argument of type 'NoneType' is not iterable
```

**Comment by legoguy1000** [comment]
I tried to setup SSO with DFIR and got the same error as @richarson

**Comment by legoguy1000** [comment]
FYI, i am getting this since the OIDC library isn't trusting my custom CA used by keycloak. I think there should be an exposed config parameter to be able to set the CA.

```
2024-12-06 15:45:38 :: ERROR :: base :: http_request :: http_request failed: HTTPSConnectionPool(host='sso.kit1.lan', port=443): Max retries exceeded with url: /realms/icarus/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1147)'))), url: https://sso.kit1.lan/realms/icarus/.well-known/openid-configuration, htargs: {'allow_redirects': True, 'cert': None, 'verify': True, 'timeout': 5.0}, method: GET
2024-12-06 15:45:38 :: WARNING :: oidc_handler :: get_oidc_client :: Could not read OIDC metadata, using environment variables - error HTTPSConnectionPool(host='sso.kit1.lan', port=443): Max retries exceeded with url: /realms/icarus/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1147)')))
```

**Comment by StaSys846** [comment]
I support this FR. 
As a workaround we use the env variable REQUESTS_CA_BUNDLE pointing to a custom CA bundle in the iris image. The env is used by default by the python requests library which is also used for the OIDC library. This will help to enable custom cert usage in IRIS OIDC.

**Comment by legoguy1000** [comment]
Is there any plan to add role mapping with OIDC so users permissions are automatic vs having to assign them after login?

**Comment by legoguy1000** [comment]
I figured out my issue. I don't use email for the username and currently ur hardcoded to use email for both the login username and the email field which causes the conflict. I think adding additional configuration to allow the users to set the fields to use.

**Comment by legoguy1000** [comment]
I submitted to https://github.com/dfir-iris/iris-web/pull/652 to add additional breakout of field mappings

**Comment by richarson** [comment]
I just upgraded to v2.4.18 and get the same error when trying to login via SSO.

**Comment by legoguy1000** [comment]
u need to set the `REQUESTS_CA_BUNDLE ` env var which sets the custom CA for all of python requests OR i found u can set `verify_ssl` env var and it will set the setting just for the OIDC library.

**Comment by richarson** [comment]
> u need to set the `REQUESTS_CA_BUNDLE ` env var which sets the custom CA for all of python requests OR i found u can set `verify_ssl` env var and it will set the setting just for the OIDC library.

Hi @legoguy1000 thanks and sorry if I'm being too dense but I can't find any reference to REQUESTS_CA_BUNDLE in iris' docs.

Where would I put my root CA and how do I reference it in the .env?

I tried placing it in certificates/root_ca.crt and referencing it like this:
```
REQUESTS_CA_BUNDLE=root_ca.crt
```

Then I tried this:
```
REQUESTS_CA_BUNDLE=/home/iris/certificates/root_ca.crt
```

But it didn't work:
```
[root@server iris-web] # docker compose logs | grep myoidc.mydomain.tld
iriswebapp_app       | 2024-12-12 16:15:21 :: ERROR :: base :: http_request :: http_request failed: HTTPSConnectionPool(host='myoidc.mydomain.tld', port=443): Max retries exceeded with url: /oauth2/token/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)'))), url: https://myoidc.mydomain.tld/oauth2/token/.well-known/openid-configuration, htargs: {'allow_redirects': True, 'cert': None, 'verify': True, 'timeout': 5.0}, method: GET
iriswebapp_app       | 2024-12-12 16:15:21 :: WARNING :: oidc_handler :: get_oidc_client :: Could not read OIDC metadata, using environment variables - error HTTPSConnectionPool(host='myoidc.mydomain.tld', port=443): Max retries exceeded with url: /oauth2/token/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))
iriswebapp_worker    | 2024-12-12 16:15:49 :: ERROR :: base :: http_request :: http_request failed: HTTPSConnectionPool(host='myoidc.mydomain.tld', port=443): Max retries exceeded with url: /oauth2/token/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)'))), url: https://myoidc.mydomain.tld/oauth2/token/.well-known/openid-configuration, htargs: {'allow_redirects': True, 'cert': None, 'verify': True, 'timeout': 5.0}, method: GET
iriswebapp_worker    | 2024-12-12 16:15:49 :: WARNING :: oidc_handler :: get_oidc_client :: Could not read OIDC metadata, using environment variables - error HTTPSConnectionPool(host='myoidc.mydomain.tld', port=443): Max retries exceeded with url: /oauth2/token/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))
```

**Comment by legoguy1000** [comment]
The REQUESTS_CA_BUNDLE env var is not an IRIS specific thing, its python requests library override that's being used several layers below. You can place the root CA anywhere and just set the ENV var to the path of the file as u have. Make sure the permissions are set to allow the user running IRIS/Python to read it. Also if there are intermediate CAs, those need to be in the file too, the entire chain.

**Comment by richarson** [comment]
Thank you @legoguy1000 , closer but not there yet.

Now I'm getting "Your application's callback URL does not match with the registered redirect URLs" from my OIDC provider (WSO2 Identity Server).

I don't know what should I use as a callbak/redirect URL, I tried these but none worked:

```
https://iris.domain.tld/
https://iris.domain.tld/*
https://iris.domain.tld/oidc-login
https://iris.domain.tld/login
https://iris.domain.tld/login?next=/
https://iris.domain.tld/login?next=/dashboard?
```

**Comment by richarson** [comment]
OK, I just saw in the docs:

> On the OIDC provider, the URI to set is /oidc_authorize

BUT, it's actually `/oidc-authorize` (with a dash, not an underscore).

Now I have to see how to map my data 'cause I got my email as name and my full name as username and email 😄

**Comment by baimard** [comment]
This configuration in authelia return none for user name and email ... that create user none :'(
```
 - client_id: 'secret'
        client_name: 'IRIS'
        public: false
        client_secret: secret'
        authorization_policy: two_factor
        require_pkce: false
        redirect_uris:
          - 'https://se.tld.fr/oidc-authorize'
        scopes: ['openid', 'profile', 'email', 'groups']
        response_types: 
          - code
        grant_types: 
          - 'authorization_code'
        token_endpoint_auth_method: 'client_secret_basic'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        consent_mode: implicit
```

in my docker conf in iris : 

      - OIDC_ISSUER_URL=https://secret.tld.fr
      - OIDC_CLIENT_ID=secret
      - OIDC_CLIENT_SECRET=secret
      - OIDC_AUTH_ENDPOINT=https://secret.tld.fr/api/oidc/authorization
      - OIDC_TOKEN_ENDPOINT=https://secret.tld.fr/api/oidc/token
      - OIDC_USERINFO_ENDPOINT=https://secret.tld.fr/api/oidc/userinfo


<img width="888" height="294" alt="Image" src="https://github.com/user-attachments/assets/ef4b8ded-1de6-4a96-93c5-ac0dd9ff421c" />

Any idea ?

**Comment by OEBBleo** [comment]
Can I suggest to close this?
OIDC is implemented and generally works. While it still has rough edges and it took me weeks to get it running but it works. But this issue has morphed into a 'specific OIDC support cases' thread. I suggest to open more specific issues.
