### ISSUE TITLE
[BUG] ERROR:  function gen_random_uuid() does not exist at character 83 since version 2.4.0

### ISSUE THREAD

**Issue by IOTech17** [dfir-iris/iris-web#388]
**Describe the bug**
When deploying the stack I can see this error on both the db :

ERROR:  function gen_random_uuid() does not exist at character 83

and in the app container : 

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function gen_random_uuid() does not exist
LINE 4:  org_uuid UUID DEFAULT gen_random_uuid() NOT NULL, 

**To Reproduce**
Followed the steps in the readme and also try deploying the image via portainer stack calling the env file via stack.env

I am using Fedora Core OS as docker host and to build the image

**Comment by whikernel** [comment]
Hi, thanks for reporting. 

This is the same issue as #387. We're looking into it, please see https://github.com/dfir-iris/iris-web/issues/387#issuecomment-1900199038

**Comment by whikernel** [comment]
This should now be fixed in v.2.4.4.

**Comment by IOTech17** [comment]
@whikernel 

I tried with version 2.4.5, same error :

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function gen_random_uuid() does not exist
LINE 4:  org_uuid UUID DEFAULT gen_random_uuid() NOT NULL,

**Comment by IOTech17** [comment]
@whikernel 

Yes this is exactly what I did

**Comment by whikernel** [comment]
I tried multiple times on fresh servers and I cannot reproduce the issue. The `create_user.sh` that is called at DB init should register the extension in the right `iris_db` DB.   

```
CREATE USER ${POSTGRES_ADMIN_USER} WITH CREATEDB SUPERUSER PASSWORD '${POSTGRES_ADMIN_PASSWORD}';
\c iris_db;
CREATE EXTENSION IF NOT EXISTS pgcrypto CASCADE;
```

**Comment by IOTech17** [comment]
Very interesting,

Could you try to build the image on a fedora core os instance?

I will try to build the image on another linux os

**Comment by IOTech17** [comment]
@whikernel 

I build the image on Solus OS then send the image to Dockerhub then downloaded the image via Portainer and applied the env via stack.env

```
Running iriswebapp ...
[2024-01-23 11:50:44 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2024-01-23 11:50:44 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2024-01-23 11:50:44 +0000] [7] [INFO] Using worker: eventlet
[2024-01-23 11:50:44 +0000] [9] [INFO] Booting worker with pid: 9
2024-01-23 11:50:46 :: INFO :: post_init :: run_post_init :: IRIS v2.4.5
2024-01-23 11:50:46 :: INFO :: post_init :: run_post_init :: Running post initiation steps
2024-01-23 11:50:46 :: INFO :: post_init :: run_post_init :: Attempting to connect to the database...
2024-01-23 11:50:46 :: INFO :: post_init :: run_post_init :: Connecting to database, attempt 1/3
2024-01-23 11:50:46 :: INFO :: post_init :: run_post_init :: Creating all Iris tables
2024-01-23 11:50:46 :: ERROR :: views :: <module> :: Post init failed. IRIS not started
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist
LINE 4:  org_uuid UUID DEFAULT gen_random_uuid() NOT NULL, 
                               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by IOTech17** [comment]
@whikernel which os are you using to build the image? Wouldn't it be better to provide official image directly via dockerhub?

**Comment by whikernel** [comment]
@IOTech17 I tested on Ubuntu 24 and Debian 12, freshly installed and I have not this issue anymore.  

We're not providing images directly on DockerHub mostly because we're lacking resources to do so. Any help with that is more than welcome! Ideally that should be done through the CI/CD once a release is done.  

But that wouldn't solve your current issue because the addition of the PG extension is done through a bash script ran in the Postgres instance at boot time. 
Are you using our Postgres from the docker-compose, or your own Postgres?

**Comment by IOTech17** [comment]
@whikernel 

I am using the image build from the docker-compose build. I tried building the image from 2 different Linux OS (Solus OS and Fedora Core OS)

You can try to contact https://www.linuxserver.io/ to help you with the automation for the image ,they have automated the build of many docker image.

**Comment by IOTech17** [comment]
@whikernel Same problem when building the image via a ubuntu wsl instance (ubuntu 22.04).

I then sent the image to dockerhub then download it via portainer and apply the env via stack.env

**Comment by IOTech17** [comment]
@whikernel 

Ok, it seems that the image only work if the host is debian/ubuntu and the docker compose is called directly using docker-compose up -d from the iris-web directory and not via portainer which is very strange

**Comment by IOTech17** [comment]
What I do not understand is why the script is not being called despite the fact that I am using the image built via the command docker-compose build?

**Comment by whikernel** [comment]
Hi @IOTech17 
You should be able to built the IRIS on other systems than Ubuntu and Debian. We didn't get the chance to test it out yet, but we will. 
We didn't contact linuxserver.io, we're just lacking time to do so. Publishing the image is something we meant to do for a while. We want to add it over CI/CD, and add testing in the middle. #395 is a step toward it. 

As for the script, it's a good question why it's not calling it. There are visibly quite some issues for deploying IRIS with via portainer that we're going to look into.

**Comment by genseirin** [comment]
I had the same error.

First I went with a shell into the `iriswebapp_db` container and ran `psql -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' iris_db postgres`.

I also had to change the `POSTGRES_PASSWORD` with the output of the recommended `openssl rand -base64 64`. Before I had a password with special characters `!\,%]'>`.

At some point I did `docker volume rm` to reset the installation, rebuilt several times, I don't remember in which order. Now all looks good.

**Comment by AxFrancois** [comment]
> This should now be fixed in v.2.4.4.

@whikernel I just did a fresh install on version 2.4.14 using helm chart with iriswebapp_db as db and the issue is still happening. 
Just in cas anyone find has the same issue, you can use 
`kubectl exec [pod name] -- psql -U [db username] -d [db name]-c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' ` to fix it but it's very annoying that it's not working out of the box
