### ISSUE TITLE
[BUG] duplicate key value violates unique constraint "user_api_key_key"

### ISSUE THREAD

**Issue by genseirin** [dfir-iris/iris-web#588]
**Describe the bug**
Site is inaccessible, error log of iriswebapp_app shows `duplicate key value violates unique constraint "user_api_key_key"`.

**To Reproduce**
Steps to reproduce the behavior are unknown. We noticed it recently.

**Expected behavior**
The website should be accessible and no errors in the logs.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Browser: Firefox 130
 - Version: iris-web v2.4.12 (Docker)

**Additional context**
Output with `docker logs` for container of iriswebapp_app:

```
2024-09-16 08:06:07 :: ERROR :: views :: <module> :: Post init failed. IRIS not started
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "user_api_key_key"
DETAIL:  Key (api_key)=(<STRING>) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/iriswebapp/app/views.py", line 117, in <module>
    run_post_init(development=app.config["DEVELOPMENT"])
  File "/iriswebapp/app/post_init.py", line 234, in run_post_init
    admin, pwd = create_safe_admin(def_org=def_org, gadm=gadm)
  File "/iriswebapp/app/post_init.py", line 1063, in create_safe_admin
    db.session.commit()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 598, in commit
    return self._proxied.commit()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1227, in _emit_insert_statements
    result = connection.execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "user_api_key_key"
DETAIL:  Key (api_key)=(<STRING>) already exists.

[SQL: INSERT INTO "user" ("user", name, email, uuid, password, ctx_case, ctx_human_case, active, api_key, external_id, in_dark_mode, has_mini_sidebar, has_deletion_confirmation, is_service_account, mfa_secrets, webauthn_credentials, mfa_setup_complete) VALUES (%(user)s, %(name)s, %(email)s, %(uuid)s::UUID, %(password)s, %(ctx_case)s, %(ctx_human_case)s, %(active)s, %(api_key)s, %(external_id)s, %(in_dark_mode)s, %(has_mini_sidebar)s, %(has_deletion_confirmation)s, %(is_service_account)s, %(mfa_secrets)s, %(webauthn_credentials)s, %(mfa_setup_complete)s) RETURNING "user".id]
[parameters: {'user': 'administrator', 'name': 'administrator', 'email': 'administrator@localhost', 'uuid': UUID('b3a9f354-fd5f-4b24-a80f-741764089df0'), 'password': '<HASHED PW>', 'ctx_case': None, 'ctx_human_case': None, 'active': True, 'api_key': '<STRING>', 'external_id': None, 'in_dark_mode': None, 'has_mini_sidebar': False, 'has_deletion_confirmation': False, 'is_service_account': False, 'mfa_secrets': None, 'webauthn_credentials': '[]', 'mfa_setup_complete': False}]

```

**Comment by whikernel** [comment]
Hi! 
By any chance did you set IRIS_ADM_API_KEY in the .env? 
The API KEY should be unique, so maybe you already have a user with the same key? Or you renamed the administrator, and then changed it back?

**Comment by genseirin** [comment]
Yes, I used IRIS_ADM_API_KEY in .env, it could have to do with the Wazuh integration. I commented it out and now I have a nginx issue, but that's something else. Thank you!
