### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Koayzvdp** [dfir-iris/iris-web#624]
**Describe the bug**
The docker-compose doesnt finish its setup because of a failure in the spunk and pip department. Ive tried updating them aswell but nothing seems to work. 

**To Reproduce**
1. Filling in this in terminal: the docker-compose build
2. error occurs

**Expected behavior**
That the build succesfully installs

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Smartphone (please complete the following information):**
N/A

**Additional context**
The following error occurs: Installing collected packages: WTForms, wcwidth, Wand, tinynetrc, pytz, python-gnupg, python-dotenv, pyminizip, iris-webhooks-module, iris-interface, iris-evtx, iris-check-module, entrypoint2, easyprocess, certifi, billiard, azure-common, zipp, wrapt, vine, urllib3, tzdata, typing-extensions, tqdm, toml, six, setuptools, semantic-version, rpds-py, pyunpack, pyparsing, PyJWT, pygments, pycparser, pyasn1, publicsuffixlist, psycopg2-binary, prompt-toolkit, portalocker, oauthlib, mistletoe, mdurl, marshmallow, MarkupSafe, lxml, itsdangerous, isodate, idna, h11, greenlet, future, dnspython, decorator, click, charset-normalizer, chardet, blinker, bidict, bcrypt, attrs, wsproto, Werkzeug, SQLAlchemy, requests, referencing, ratelim, python-docx, python-dateutil, packaging, markdown-it-py, Mako, ldap3, Jinja2, importlib-metadata, gunicorn, eventlet, deprecated, click-repl, click-plugins, click-didyoumean, click-creds, cffi, amqp, virustotal-api, SQLAlchemy-Utils, SQLAlchemy-ImageAttach, splunk-hec, simple-websocket, rich, requests-oauthlib, marshmallow-sqlalchemy, kombu, jsonschema-specifications, geocoder, Flask, docxtpl, docxcompose, cryptography, azure-core, alembic, python-engineio, pyintelowl, msrest, jsonschema, iris-vt-module, Flask-WTF, Flask-SQLAlchemy, flask-marshmallow, Flask-Login, Flask-Caching, Flask-Bcrypt, evtx2splunk, docx-generator, celery, python-socketio, pymisp, msal, iris-intelowl-module, azure-keyvault-secrets, msal-extensions, iris-misp-module, flask-socketio, azure-identity
  DEPRECATION: pyminizip is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyminizip: started
  Running setup.py install for pyminizip: finished with status 'done'
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  DEPRECATION: python-docx is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for python-docx: started
  Running setup.py install for python-docx: finished with status 'done'
  DEPRECATION: splunk-hec is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for splunk-hec: started
  Running setup.py install for splunk-hec: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for splunk-hec did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      /opt/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running `setup.py directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-etdv7hax/splunk-hec_49e14f0213724e40b891c11171c9bc8c/setup.py", line 13, in <module>
          setup(name='Splunk-HEC',
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/opt/venv/lib/python3.9/site-packages/setuptools/dist.py", line 991, in run_command
          super().run_command(command)
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 972, in run_command
          cmd_obj.ensure_finalized()
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/opt/venv/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in finalize_options
          super().finalize_options()
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 408, in finalize_options
          'dist_fullname': self.distribution.get_fullname(),
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/opt/venv/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> splunk-hec

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'app' failed to build : Build failed

Ive tried several things. Ive updated all the python3 and pip and downloaded the requirements.txt file but the errors keeps occuring. It seems to be a combination splunk and the pip3 install failing. I try to update the pip but i get an error saying externally managed environment,

**Comment by stysos** [comment]
Seems to be an issue with packaging version 22.0? Changing the Python version in the Dockerfile for the webapp in both stages to 3.12 fixes this problem, no idea if it has any knock on effects though.

**Comment by sp4ir** [comment]
@stysos how do you remove the version requirement?

**Comment by sp4ir** [comment]
> @stysos how do you remove the version requirement?

Answered my own question.
Note for others; update `source/requirements.txt` and change `packaging==21.3` to `packaging>=22.0`

**Comment by whikernel** [comment]
Hi @sp4ir, @stysos 

The docker compose build step is no longer required as we publish pre build docker images. This step should be replaced by docker compose pull. 
Kindly check the latest version of the documentation: https://docs.dfir-iris.org/latest/operations/upgrades/

I will close this issue
